resources:
- name: repo
  type: git
  source:
    uri: https://github.com/yutaokamoto/concourse-ci-catchup.git

jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]